# Generated by Django 3.1.1 on 2021-06-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
